version: '3.7'
services:
    database:
        image: mysql:8.0.32
        environment:
            - MYSQL_ROOT_PASSWORD=not_admin
            - MYSQL_USER=masbro
            - MYSQL_PASSWORD=mantap
            - MYSQL_DATABASE=vtuber_db
        ports:
            - 3306:3306
        volumes:
            - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    adminer:
        image: adminer
        ports:
        - 8080:8080
        links:
            - database
            
    object_storage:
        image: bitnami/minio:latest
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minio-root-user
            - MINIO_ROOT_PASSWORD=minio-root-password

    frontend_server:
        build: ./vtuber-frontend-service
        ports:
            - 3000:3000
        # env_file:
        #     - ./vtuber-frontend-server/.env.example
        volumes:
            - ./vtuber-frontend-service:/app
            - /app/node_modules
            - /app/.next
        links:
            - database:mysql
            - video_service:video
            - discography_service:discography
            - art_service:art
    
    video_service:
        build: ./vtuber-video-services
        ports:
            - 8000:8000
        env_file:
            - ./vtuber-video-services/.env
        volumes:
            - ./vtuber-video-services:/project
        depends_on:
            - database
        links:
            - database:mysql
        
    discography_service:
        build: ./vtuber-discography-services
        ports:
            - 8001:8000
        env_file:
            - ./vtuber-discography-services/.env.example
        volumes:
            - ./vtuber-discography-services/app:/app/app
            - ./vtuber-discography-services/config:/app/config
            - ./vtuber-discography-services/database:/app/database
            - ./vtuber-discography-services/public:/app/public
            - ./vtuber-discography-services/resources:/app/resources
            - ./vtuber-discography-services/routes:/app/routes
            - ./vtuber-discography-services/tests:/app/tests
            - ./vtuber-discography-services/composer.json:/app/composer.json
            - ./vtuber-discography-services/composer.lock:/app/composer.lock
            - ./vtuber-discography-services/package.json:/app/package.json
        depends_on:
            - database
        links:
            - database:mysql
        restart: on-failure
        
    art_service:
        build: ./vtuber-art-services
        ports:
            - 3001:3000
        # env_file:
        #     - ./vtuber-art-services/.env.example
        volumes:
            - ./vtuber-art-services:/usr/local/apps/app/dev
        depends_on:
            - database
        links:
            - database:mysql