version: '3.7'
services:
    database:
        image: mariadb:10.4.21
        # volumes: 
        #     - ../database_dump:/docker-entrypoint-initdb.d/
        environment:
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_USER=masbro
            - MARIADB_PASSWORD=mantap
        ports:
            - 3306:3306

    object_storage:
        image: bitnami/minio:latest
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minio-root-user
            - MINIO_ROOT_PASSWORD=minio-root-password

    frontend_server:
        build: ./vtuber-frontend-service
        ports:
            - 3000:3000
        env_file:
            - ./vtuber-etl-service/.env.example
        links:
            - database:mysql
    
    video_service:
        build: ./vtuber-video-services
        ports:
            - 8000:8000
        env_file:
            - ./vtuber-video-services/.env.example
        volumes:
            - ./vtuber-video-services:/project
        depends_on:
            - database
        links:
            - database:mysql